# Generated by Django 6.0.7 on 2026-07-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
